[package]
name = "smart_ape"
version = "0.1.1"
edition = "2021"
description = "A genetic algorithms library."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
